trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
- stage: BuildAndPublish
  displayName: BuildAndPublish
  jobs:
  - job: Build
    steps:
    - task: DotNetCoreCLI@1
      inputs:
        command: build
      displayName: Build
    - task: DotNetCoreCLI@1
      inputs:
        command: publish
        arguments: --configuration release --output $(Build.ArtifactStatingDirectory)
        zipAfterPublish: true
      displayName: dotnet publish
