trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  resourceGroupName: 'student-training'
  serviceConnection: 'student-training'
  webAppName: 'student-training' 

stages:
- stage: BuildAndPublish
  displayName: BuildAndPublish
  jobs:
  - job: DeployInfra
    steps:
    - task: AzureCLI@2
      inputs:
        scriptType: bash
        azureSubscription: $(serviceConnection)
        arguments: --file $(System.DefaultWorkingDirectory)/infra/main.bicep --outdir $(System.DefaultWorkingDirectory)/main.json
        inlineScript:  az bicep build
      displayName: Transiple Bicep to ARM

    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: $(serviceConnection)
        resourceGroupName: ${{ resourceGroupName }}
        csmFile: $(System.DefaultWorkingDirectory)/main.json
        overrideParameters: >-
          -webAppName ${{ webAppName }}

  - job: BuildAndDeployCode
    steps:
    - task: DotNetCoreCLI@1
      inputs:
        command: build
      displayName: Build

    - task: DotNetCoreCLI@1
      inputs:
        command: publish
        arguments: --configuration release --output publishPackage
        zipAfterPublish: true
      displayName: dotnet publish

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: $(System.DefaultWorkingDirectory)/publishPackage
        ArtifactName: 'publishPackage'
      displayName: Publish Artifact

- stage: DeployWebApp
  dependsOn: BuildAndPublish
  displayName: Deploy Web API Code
  jobs:
  - job: DownloadPackageAndDeploy
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: 'publishPackage'
          path: $(System.DefaultWorkingDirectory)
      
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: ${{ serviceConnection }}
          appType: 'webAppLinux'
          WebAppName: 'wapp-student-training'
          ResourceGroupName: ${{ resourceGroupName }}
          packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'