trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  resourceGroupName: 'student-training'
  serviceConnection: 'student-training'
  webAppName: 'student-training' 

stages:
- stage: BuildAndPublish
  displayName: BuildAndPublish
  jobs:
  - job: DeployInfra
    steps:
    - bash: az bicep build --file "infra/main.bicep" --outfile "infra/main.json"
      displayName: Transiple Bicep to ARM

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: Resource Group
        action: Create Or Update Resource Group
        location: 'South Africa North'
        azureResourceManagerConnection:  $(serviceConnection)
        resourceGroupName: $(resourceGroupName)
        csmFile: 'infra/main.json'
        deploymentMode: Incremental
        templateLocation: Linked artifact
        overrideParameters: >-
          -webAppName $(webAppName)
      displayName: Override Parameters

  - job: BuildAndPublish
    dependsOn: DeployInfra
    steps:
    - task: DotNetCoreCLI@1
      inputs:
        command: build
        projects: $(System.DefaultWorkingDirectory)/**/*.csproj
      displayName: Build

    - task: DotNetCoreCLI@1
      inputs:
        command: publish
        projects: $(System.DefaultWorkingDirectory)/**/*.csproj
        arguments: --configuration release --output $(Pipeline.Workspace)/publish
        zipAfterPublish: true
        publishWebProjects: false
      displayName: dotnet publish

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/publish'
        artifactName: publishPackage
        artifactType: 'pipeline'
      displayName: Publish Artifact

- stage: DeployWebApp
  dependsOn: BuildAndPublish
  displayName: Deploy Web API Code
  jobs:
  - job: DownloadPackageAndDeploy
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          source: 'current'
          artifactName: 'publishPackage'
          path: $(System.DefaultWorkingDirectory)/publish
      
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: $(serviceConnection)
          appType: 'webAppLinux'
          WebAppName: 'wapp-student-training'
          ResourceGroupName: $(resourceGroupName)
          packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'